config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'artworks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artworks do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:create]
  end
  get '/users/dashboard', to: 'users#dashboard'
  resources :users, only: [:show]
  resources :bookings, only: [] do
    member do
      get :accept
      get :decline
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search_by_name,
    against: [:name, :category],
    associated_against: {
      user: [:name]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :artwork
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :artwork
  validates :content, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :artworks, dependent: :destroy
  has_many :bookings, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :name, :category, :artist, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :category, :artist, :photo])
  end

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index

  def index
    if params[:query].present?
      @artworks_for_list = Artwork.search_by_name(params[:query])
    else
      @artworks_for_list = Artwork.all
    end

    @artworks_for_markers = Artwork.where.not(latitude: nil, longitude: nil)
    @markers = @artworks_for_markers.map do |artwork|
      {
        lng: artwork.longitude,
        lat: artwork.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { artwork: artwork }),
        # image_url: helpers.asset_url('paint_brush.png')
      }
    end
  end

  def show
    @booking = Booking.new
    @artwork = Artwork.find(params[:id])
    @review = Review.new
    authorize @artwork
  end

  def new
    @user = current_user
    @artwork = Artwork.new
    authorize @artwork
  end

  def create
    @artwork = Artwork.new(artwork_params)
    authorize @artwork
    @artwork.user = current_user
    if @artwork.save
      redirect_to artwork_path(@artwork)
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @artwork = Artwork.find(params[:id])
    authorize @artwork
  end

  def update
    @artwork = Artwork.find(params[:id])
    authorize @artwork
    @artwork.user = current_user
    @artwork.update(artwork_params)
    redirect_to artwork_path(@artwork)
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    authorize @artwork
    @artwork.destroy
    redirect_to artworks_path
  end

  private

  def artwork_params
    params.require(:artwork).permit(:name, :category, :photo, :availability, :start_date, :end_date, :address, :price)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @artwork = Artwork.find(params[:artwork_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.artwork = Artwork.find(params[:artwork_id])
    @booking.user = current_user
    if @booking.save
      redirect_to artwork_path(@booking.artwork)
    else
      render "artworks/show"
    end
  end

  def accept
    skip_authorization
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to users_dashboard_path
  end

  def decline
    skip_authorization
    @booking = Booking.find(params[:id])
    @booking.status = "refused"
    @booking.save
    redirect_to users_dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :date_start, :date_finish)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @artwork = Artwork.find(params[:artwork_id])
    @review = Review.new(review_params)
    authorize @review
    @review.artwork = @artwork
    if @review.save
      respond_to do |format|
        format.html { redirect_to artwork_path(@artwork) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'artworks/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def dashboard
    skip_authorization
    @user = current_user
    @user.artworks.each do |artwork|
      artwork.bookings.each do |booking|
        @booking = booking
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_infowindow.html.erb
<h4><%= artwork.name %></h4>
<%= cl_image_tag artwork.photo, height: 100, width: 200, crop: :fill %>

app/views/artworks/edit.html.erb
<div class="container">

  <div class="row">

    <div class="col-sm-offset-3 col-sm-6">

    <div class="edit-title">
      <h1>Modify my offer </h1>
    </div>

      <%= simple_form_for(@artwork) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :category %>
          <%= f.text_field :category, class: 'form-control' %>
        </div>

         <div class="form-group">
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
        </div>

        <div class="form-wrapper" style="width: 570px; margin: 0 auto;">
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.submit class: 'btn btn-primary' %>
          <%= link_to artwork_path(@artwork), class: 'btn btn-danger',
            method: :delete, data: { confirm: "Are you sure?" } do %>
              <i class="far fa-trash-alt"></i>
           <% end %>
        </div>

      <% end %>

      <%= link_to artwork_path(@artwork) do %>
        <i class="fas fa-undo-alt"></i>
      <% end %>
    </div>

  </div>

</div>

app/views/artworks/index.html.erb
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0.4) 50%), url('<%= image_path 'banner.jpg' %>');">
  <div class="banner-content">
    <h1> Art Spirit </h1>
    <p> Decorate your life </p>
  </div>
</div>

<div class="container">
  <div id="anchor_search"> </div>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <%= form_tag artworks_path, method: :get do %>

      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find an artwork"
      %>
      <% end %>
    </div>
  </div>
</div>

<div class="main-container">
  <div class="row main-row">
    <% @artworks_for_list.each do |artwork|  %>

      <div class="col-xs-12 col-sm-4 card-height">

        <div class="cards">

          <%= link_to artwork_path(artwork) do  %>
            <div class="card" style="background-image: url('<%= artwork.photo.url ? (cl_image_path artwork.photo, height: 300, width: 300, fetch_format: :auto) : "https://media.cargocollective.com/1/22/726497/headerimg/FERGUS-WORK02188-copie.png"; %>')">
            </div>
          <% end %>
          <div class="card-description">
            <h3>
              <% if policy(Artwork).show? %>
                <%= link_to artwork.name, artwork_path(artwork) %>
              <% end %>
            </h3>
            <p><%= artwork.category %></p>
            <% if artwork.price.present? %>
              <p><%= artwork.price %><i class="fas fa-euro-sign"></i> per day</p>
            <% end %>
            <ul>
              <div class="user-name">
                <li> <%= cl_image_tag artwork.user.photo.url(:bright_face) %></li>
                <li><p><%= link_to artwork.user.name, user_path(artwork.user) %></p></li>
              </div>
            </ul>
          </div>

        </div>
      </div>
    <% end %>
  </div>
  <div
    id="map"
    style="width: 100%;
    height: 830px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright"></div>
</div>

app/views/artworks/new.html.erb
<div class="container">

  <div class="row">

    <div class="col-sm-offset-3 col-sm-6">

      <div class="form-title">
        <h1>Expose your art</h1>
      </div>

      <%= simple_form_for(@artwork) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class=“form-group”>
         <% @categories = ['painting', 'sculpture', 'drawing', 'photo'] %>
          <%= f.input :category, collection: @categories %>
        </div>

        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_field :address, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= image_tag "", width: 300 , class: "hidden", id: "photo-preview" %>
          <%= f.input :photo, input_html: { class: 'hidden', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>

           <%= f.input :photo_cache, as: :hidden %>
        </div>

        <div class="form-group calendar" style="width: 570px; margin: 0 auto; padding: 0px">
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        </div>

        <div class="form-group">
         <%= f.label :price %>
         <%= f.text_field :price, class: 'form-control' %>
        </div>

       <%= f.submit class: 'btn btn-primary' %>
      <% end %>

    </div>

  </div>

</div>

app/views/artworks/show.html.erb
<div class="container ">

  <div class="wrapper ">

    <div class="flex-booking">

      <div class="artwork-content">
        <h1> <%= @artwork.name %> </h1>
        <h3><small>Made by: </small><%= link_to @artwork.user.name, user_path(@artwork.user) %></h3>
        <p> <% @artwork.user.category %></p>
        <%= cl_image_tag @artwork.photo, height: 480, width: 600, fetch_format: :auto %>
        <% if policy(@artwork).edit? %>

          <div class="edit">
            <%= link_to  edit_artwork_path(@artwork) do %>
            <i class="fas fa-edit"></i>
            <%end %>
          </div>
        <%end %>
        <p class="align-center"> <%= @artwork.category %> </p>
      </div>

      <div class="row-show">
        <div class="artwork-booking">
          <div class="info-right">
            <h3><small>Available from : </small></h3>
            <h3> <%= @artwork.start_date %> to : <%= @artwork.end_date %></h3>
            <h3><small> Price : <%= @artwork.price %> €</small></h3>
          </div>
          <h2> Book this artwork: </h2>
          <%= simple_form_for [@artwork, @booking] do |f| %>
            <div class="form-group calendar" style="width: 400px; margin: 0 auto;">
              <%= f.input :date_start, as: :string, required: false, input_html: {class: "datepicker"} %>
              <%= f.input :date_finish, as: :string, required: false, input_html: {class: "datepicker"} %>
              <p class="align-center">
                <%= f.submit "send", class: "btn btn-primary" %>
              </p>
            </div>
          <% end %>
        </div>
        <!-- </div> -->
      </div>
    </div>
    <div>
      <h2><%= pluralize @artwork.reviews.size, "review" %></h2>
    </div class="review">
      <div id="reviews">
        <%= render 'reviews/form', artwork: @artwork, review: @review %>
        <% if @artwork.reviews.blank? %>
          Be the first to leave a review for <%= @artwork.name %>
        <% else %>
          <% @artwork.reviews.each do |review| %>
            <%= render 'reviews/show', review: review %>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h1>Test</h1>
<%= form_for [@artwork, @booking] do |f| %>
  <%= f.input :status %>
  <%= f.submit "book an artwork", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RentArt</title>
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'shared/navbar' %>
   <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for([ @artwork, review ], remote: true) do |form| %>
  <%= form.input :content, as: :text, label: false %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<p><%= review.content %></p>

app/views/reviews/_show.js.erb
<p><%= review.content %></p>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<%if @review.errors.any?%>
  refreshForm('<%= j render "reviews/form", artwork: @artwork, review: @review %>');
<%else%>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", artwork: @artwork, review: Review.new %>');
<%end%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon ">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "art.png", height: 45 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <% current_user.artworks.each do |artwork|%>
        <% if artwork.bookings.any? {|booking| booking.status == "pending" } %>
          <div class="animation">
          <span><%= link_to "Dashboard", "/users/dashboard", id:"custom", class: "navbar-wagon-item navbar-wagon-link" %></span>
          </div>
        <%else %>
          <%= link_to "Dashboard", "/users/dashboard", class: "navbar-wagon-item navbar-wagon-link" %>
        <%end %>
      <%end %>

      <%= link_to "Create artwork", "/artworks/new", class: "navbar-wagon-item navbar-wagon-link" %>



      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
            <%= link_to "update your profile", edit_user_registration_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container">
<div class="bookings">
<%if @user.artist == false%>

<%@user.bookings.each do |booking|%>
  <% if booking.status == "pending" %>
      <h2> Your booking has not yet been confirmed</h2>
      <div class="book">
      <h3><%= booking.artwork.name %></h3>
      <%= cl_image_tag booking.artwork.photo, height: 500, width: 600, crop: :fill %>
      <p>start :<%= booking.date_start%></p>
      <p>end :<%= booking.date_finish %></p>
      </div>
    <%end %>
<%end %>

<%@user.bookings.each do |booking|%>
  <% if booking.status == "accepted" %>
   <div class="book">
    <h2>Your booking has been accepted !</h2>
    <h3><%= booking.artwork.name %></h3>
    <%= cl_image_tag booking.artwork.photo, height: 500, width: 600, crop: :fill %>
    <p>start :<%= booking.date_start%></p>
    <p>end :<%= booking.date_finish %></p>
    </div>
  <%end %>
<%end %>

  <%@user.bookings.each do |booking|%>
  <% if booking.status == "deleted" %>
    <h2>Bookings rejected</h2>
    <div class="book">
    <h3><%= booking.artwork.name %></h3>
    <%= cl_image_tag booking.artwork.photo, height: 500, width: 600, crop: :fill %>
    <p>start :<%= booking.date_start%></p>
    <p>end :<%= booking.date_finish %></p>
    </div>
  <%end %>
<%end %>

<%end %>

<%if @user.artist  %>
  <div class="flexbooking">
    <div class="pending">
      <%@user.artworks.each do |artwork|%>
        <%artwork.bookings.each do |booking|  %>
          <% if booking.status == "pending" %>
            <h2> Booking requests </h2>
            <h3><%= booking.artwork.name %></h3>
            <%= cl_image_tag booking.artwork.photo, height: 500, width: 600, crop: :fill %>
            <p>start :<%= booking.date_start%></p>
            <p>end :<%= booking.date_finish %></p>
            <div class="buttons">
              <%= link_to accept_booking_path(booking) do %>
                <button type="button" class="btn btn-primary">accept</button>
              <% end %>
              <%= link_to decline_booking_path(booking) do %>
                <button type="button" class="btn btn-primary">decline</button>
              <% end %>
            </div>
          <%end %>
        <%end %>
      <%end %>
    </div>
    <div class="accepted">
      <%@user.artworks.each do |artwork|%>
        <%artwork.bookings.each do |booking|  %>
          <% if booking.status == "accepted" %>
            <h2>Artwork booked</h2>
            <h3><%= booking.artwork.name %></h3>
            <%= cl_image_tag booking.artwork.photo, height: 500, width: 600, crop: :fill %>
            <p>start :<%= booking.date_start%></p>
            <p>end :<%= booking.date_finish %></p>
          <%end %>
        <%end %>
      <%end %>
    </div>
  </div>
<%end %>
</div>
</div>

app/views/users/show.html.erb
<div class="container">

  <div class="profile">

    <div class="profile-content">
      <div class="profile-description">
        <h1><%= @user.name %></h1>
        <%if @user.artist %>
          <h4> artist </h4>
        <%else %>
          <h4>host</h4>
        <%end %>
        <h4><%= @user.category %></h4>
      </div>
      <div class="profile-photo">
        <%= cl_image_tag @user.photo,  width: 150, height: 150, crop: :thumb, gravity: :face, radius: 100 %>
      </div>
    </div>

    <div class="my-artwork">
      <h3> Artworks </h3>
      <% @user.artworks.each do |artwork| %>
        <div class="col-xs-12 col-sm-4 card-height">

          <div class="cards">

            <%= link_to artwork_path(artwork) do %>
              <div class="card" style="background-image: url('<%= cl_image_path artwork.photo, height: 300, width: 400, fetch_format: :auto %>')"></div>
            <% end %>

            <div class="card-description">
              <h3>
                <% if policy(Artwork).show? %>
                <%= link_to artwork.name, artwork_path(artwork) %>
                <% end %>
              </h3>
              <p><%= artwork.category %></p>
            </div>
            <% if policy(artwork).destroy? %>
              <div class="delete-artwork">
                <%= link_to artwork_path(artwork),
                  method: :delete, data: { confirm: "Are you sure?" } do %>
                    <i class="far fa-trash-alt"></i>
                 <% end %>
              </div>
            <% end %>
          </div>


        </div>
      <% end %>
    </div>
  </div>
</div>